title: Player 2 Games
tagline: Video game news and updates and what we think of them.
description: A podcast about video game news, history, and opinions. Hosted by Kirk and Luke.
social_image: "/assets/images/social - opengraph - banner.jpg"

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-archives

port: 3999

postcss:
  cache: false

exclude:
  - .git
  - .github
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .tool-versions
  - Gemfile
  - Gemfile.lock
  - Procfile
  - gemfiles/
  - node_modules/
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

jekyll-archives:
  enabled:
    - year
    - month
  layout: archive_index
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
