name: Publish
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Jekyll Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true

    - uses: actions/setup-node@v3
      with:
        node-version: 16.10.0

    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn
    - run: bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
